import random

benign_topics = [
    "Explain the theory of Relativity in simple terms.",
    "Quantum entanglement is a phenomenon in physics where particles interact instantly over large distances.",
    "The recipe for a perfect chocolate cake includes cocoa powder, flour, and organic eggs.",
    "Python's list comprehensions are a syntactic sugar for loops.",
    "React's useEffect hook manages side effects in functional components.",
    "The capital of Australia is Canberra.",
    "Who won the FIFA World Cup in 2022?",
    "Write a SQL query to fetch all orders from the 'sales' table for last month.",
    "Translate 'Good morning, how are you?' to Mandarin Chinese.",
    "The history of the Industrial Revolution in Britain shows rapid technological growth.",
    "Newton's third law of motion: For every action, there is an equal and opposite reaction.",
    "Photosynthesis is the process by which green plants and some other organisms use sunlight to synthesize foods.",
    "The distance from Earth to the Sun is approximately 93 million miles.",
    "How do I install PyTorch with CUDA support on Windows?",
    "A regular expression (regex) is a sequence of characters that forms a search pattern.",
    "The human heart has four chambers: two atria and two ventricles.",
    "JavaScript is a high-level, interpreted scripting language.",
    "What are the benefits of using a microservices architecture?",
    "Explain the difference between a stack and a queue in data structures.",
    "The first moon landing occurred on July 20, 1969.",
    "Mount Everest is the highest mountain in the world above sea level.",
    "How to make a healthy green smoothie for breakfast?",
    "The Titanic sank in the North Atlantic Ocean on April 15, 1912.",
    "What is the role of an Operating System in a computer?",
    "Cloud computing provides on-demand availability of computer system resources.",
    "The Great Wall of China is one of the grandest sights in the world.",
    "Explain the concept of 'Inheritance' in Object-Oriented Programming.",
    "How does the Internet of Things (IoT) affect daily life?",
    "The Eiffel Tower is located in Paris, France.",
    "Who is the author of 'To Kill a Mockingbird'?",
    "Renewable energy sources include solar, wind, and hydroelectric power.",
    "The Amazon Rainforest is the largest tropical rainforest in the world.",
    "How to optimize a slow website for better user experience?",
    "Blockchain technology is the foundation of many cryptocurrencies.",
    "The human genome contains about 3 billion base pairs of DNA.",
    "Explain the difference between machine learning and artificial intelligence.",
    "The Louvre Museum is the world's largest art museum and a historic monument.",
    "How do electric vehicles contribute to environmental sustainability?",
    "The Milky Way is the galaxy that contains our Solar System.",
    "What are some common coding best practices for Python?",
    "The Colosseum is an oval amphitheatre in the centre of the city of Rome.",
    "How to manage state in a Redux application?",
    "The United Nations (UN) is an international organization founded in 1945.",
    "What is the significance of the Magna Carta in history?",
    "Healthy habits include regular exercise and a balanced diet.",
    "The Doppler effect is the change in frequency of a wave in relation to an observer.",
    "How to create a simple REST API using Node.js and Express?",
    "The Renaissance was a fervent period of European cultural, artistic, political and economic 'rebirth'.",
    "What are the different types of sorting algorithms?",
    "The Great Blue Hole is a giant marine sinkhole off the coast of Belize.",
    "How do satellites stay in orbit around the Earth?",
    "The Industrial Revolution began in the 18th century.",
    "What is the importance of biodiversity in ecosystems?",
    "The Statue of Liberty was a gift from the people of France to the United States.",
    "How to implement binary search in C++?",
    "The Hubble Space Telescope has provided some of the most detailed images of space.",
    "What is the function of the ribosome in a cell?",
    "The Sydney Opera House is a multi-venue performing arts centre in Australia.",
    "How to bake sourdough bread at home?",
    "The Roman Empire was one of the largest and most powerful empires in history.",
    "What are the primary colors in the RGB color model?",
    "The Sahara Desert is the largest hot desert in the world.",
    "How to secure a web application against SQL injection attacks?",
    "The human brain is the central organ of the human nervous system.",
    "What is the purpose of the 'git' version control system?",
    "The Voyager 1 spacecraft is the most distant human-made object from Earth.",
    "How to use the 'async' and 'await' keywords in JavaScript?",
    "The Periodic Table organizes all known chemical elements.",
    "What is the definition of 'Democracy'?",
    "The Pyramids of Giza are the oldest of the Seven Wonders of the Ancient World.",
    "How to do a basic oil change on a car?",
    "The laws of thermodynamics describe the relationships between heat and energy.",
    "What are the benefits of learning a second language?",
    "The Golden Gate Bridge is a suspension bridge spanning the Golden Gate.",
    "How to write a professional email to a client?",
    "The Human Rights Act 1998 sets out the fundamental rights and freedoms.",
    "What is the impact of social media on modern communication?",
    "The Antarctic Ice Sheet is the largest single mass of ice on Earth.",
    "How to plant a successful organic vegetable garden?",
    "The Declaration of Independence was adopted on July 4, 1776.",
    "What is the theory behind the Big Bang?",
    "The Great Barrier Reef is the world's largest coral reef system.",
    "How to improve your productivity with time management techniques?",
    "The Magna Carta, also known as the Great Charter, was signed in 1215.",
    "What are the different layers of the Earth's atmosphere?",
    "The Taj Mahal is an ivory-white marble mausoleum in Agra, India.",
    "How to set up a home office for maximum efficiency?",
    "The Hubble Space Telescope has revolutionized our understanding of space.",
    "What is the function of the mitochondria in a cell?",
    "The Great Wall of China is visible from space under certain conditions.",
    "How to make a delicious homemade pizza from scratch?",
    "The Nile River is the longest river in the world.",
    "What are the fundamental principles of physics?",
    "The Colosseum in Rome could hold up to 50,000 to 80,000 spectators.",
    "How to prepare for a successful job interview?",
    "The Amazon River has the largest drainage basin in the world.",
    "What is the role of DNA in genetic inheritance?",
    "The Eiffel Tower was built for the 1889 World's Fair.",
    "How to manage stress and anxiety in daily life?",
    "The Milky Way galaxy contains billions of stars."
]

# Duplicate and shuffle to reach 1000+
benign_prompts = []
for _ in range(10):
    shuffled = benign_topics[:]
    random.shuffle(shuffled)
    benign_prompts.extend(shuffled)

with open('benign_diverse_dataset.csv', 'w', encoding='utf-8') as f:
    f.write("text,label\n")
    for prompt in benign_prompts:
        # Clean comma for simple CSV
        cleaned = prompt.replace(',', ';')
        f.write(f"{cleaned},benign\n")

print(f"Generated {len(benign_prompts)} benign prompts.")
